### ISSUE TITLE
请问能否指导以下，更新到新的https://github.com/ssshooter/mind-elixir-core

### ISSUE THREAD

**Issue by markqiu** [dust8/dmind#6]
@dust8 有时间指导一下呗

**Comment by dust8** [comment]
1.看notebook的文档,学他插件的开发
2.看mind-elixir-core的文档,知道怎么用
3.把他们组合在一起. 没思路的话可以看下我的源码, 才百来行

**Comment by markqiu** [comment]
谢谢指导，我试试啊，碰到问题再请教！
